#ifndef BITCOIN_CONSTANTS_H
#define BITCOIN_CONSTANTS_H

#define BITCOIN_ADDRESS_CHECKSUM_LENGTH 4
#define BITCOIN_PUBKEY_LEN 33
#define BITCOIN_SECKEY_LEN 32
#define BITCOIN_RS_SIG_LEN 65
#define BITCOIN_DER_SIG_LEN (7+33+33)

#endif
