/*
 * This file is part of the Skycoin project, https://skycoin.net/
 *
 * Copyright (C) 2018-2019 Skycoin Project
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

// Autogenerated from https://github.com/skycoin/skycoin/tree/7cc25f1cb91afe5220a2bbc2ca93177d6a91c2a0/
// WARNING: Do not edit

#ifndef __TEST_MANY_ADDRESSES_GOLDEN__

#define TEST_MANY_ADDRESS_SEED "wire junk original sword bread bottom armor dog snow accident inform rigid"

extern char TEST_MANY_ADDRESSES[100][36];

#endif // __TEST_MANY_ADDRESSES_GOLDEN__

